services:
  puppeteer-tests:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    command: ["pnpm", "run", "test:e2e"]
